# -*- coding: utf-8 -*-
"""danlc_lab5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BUddU3tSJejeaSTP0p6xG1JWenU2Phgs
"""

# First 10 natural numbers
for i in range(1, 11):
    print(i, end=" ")

# Check for palindrome
string = input("Enter a string: ")
if string == string[::-1]:
    print(f"{string} is a palindrome")
else:
    print(f"{string} is not a palindrome")

# Check for Armstrong number
number = int(input("Enter a number: "))
temp = number
sum_of_cubes = 0

while temp > 0:
    digit = temp % 10
    sum_of_cubes += digit ** 3
    temp //= 10

if sum_of_cubes == number:
    print(f"{number} is an Armstrong number")
else:
    print(f"{number} is not an Armstrong number")

# Fibonacci series between 0 and 50
a, b = 0, 1
while a <= 50:
    print(a, end=" ")
    a, b = b, a + b

# Check password validity without libraries

password = input("Enter a password: ")

# Initialize flags
has_upper = False
has_lower = False
has_digit = False
has_special = False

# Check each character in the password
for char in password:
    if char.isupper():
        has_upper = True
    elif char.islower():
        has_lower = True
    elif char.isdigit():
        has_digit = True
    elif char in "@#$%^&+=":
        has_special = True

# Check password length and flags
if len(password) >= 8 and has_upper and has_lower and has_digit and has_special:
    print("Password is valid")
else:
    print("Password is invalid")