# -*- coding: utf-8 -*-
"""danlc_lab6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i5OzKsdOwyR-gS6oGtMYz3CoSwH__lFr
"""

string = "To change the overall look of your document. To change the look available in the gallery"

# Convert the string into lowercase and split it into words
words = string.lower().split()

# Create an empty dictionary to store word counts
word_count = {}

# Count occurrences of each word
for word in words:
    word_count[word] = word_count.get(word, 0) + 1

# Display the word counts
print("Word occurrences:")
for word, count in word_count.items():
    print(f"{word}: {count}")

string = "\nBest \nDeeptech \nPython \nTraining\n"

# Remove all newlines using replace()
cleaned_string = string.replace("\n", " ")

# Display the cleaned string
print("String without newlines:")
print(cleaned_string)

string = "Deeptech Python Training"

# Split the string into words, reverse the list of words, and join them back
reversed_string = " ".join(string.split()[::-1])

# Display the reversed string
print("Reversed words:")
print(reversed_string)

string = "Welcome to python Training"

# Convert the string to lowercase for consistency
string = string.lower()

# Initialize a dictionary to store vowel counts
vowel_count = {vowel: 0 for vowel in "aeiou"}

# Count the vowels
for char in string:
    if char in vowel_count:
        vowel_count[char] += 1

# Display the vowels and their counts
print("Vowel counts:")
for vowel, count in vowel_count.items():
    print(f"{vowel}: {count}")