# -*- coding: utf-8 -*-
"""DANLC_LAB1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JGTOkH2vtSrQ8d-5jm09LX_3-vQWMZh-
"""

# 1

a = 10
b = 20
c = a*b
d = a+b
print(c)
print(d)

#2
a = 10
b = 20
x = b if a<b else a
print(x)

#3
celsius = float(input('Enter temperature in Celsius: '))
fahrenheit = (celsius * 1.8) + 32
print(f"{celsius}°C is equal to {fahrenheit}°F")

#4
import math

a = 2
b = 3
c = 4

s = (a + b + c) / 2
area = math.sqrt(s * (s - a) * (s - b) * (s - c))

print(f"The area of the triangle is: {area}")