# -*- coding: utf-8 -*-
"""DANLC_Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14fXJMFT9aarnOj7bhST6JdF46FfuWY25
"""

#1 Checking even or odd
check = int(input("Enter an integer: "))
x = print(f"{check} is an Even number") if check % 2 == 0 else print(f"{check} is an Odd number")

#2 Swapping two numbers
a = int(input("Enter 1st no.: "))
b = int(input("Enter 2nd no.: "))
print(f"Before swapping: {a}, {b}")
a,b = b,a
print(f"After swapping: {a}, {b}")

#3 Convert Kms to Miles
kms = float(input("Enter distance in kms: "))
miles = kms * 0.621371
print(f"{kms} kms = {miles} miles")

#4 Find the simple interest on ₹200 for 5 years at 5% per year

principal = 200
rate = 5
time = 5

simple_interest = (principal * rate * time) / 100

print(f"The simple interest is: ₹{simple_interest}")