# -*- coding: utf-8 -*-
"""DANLC_Lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TJyMUDXU63mLcbaX4vM5GHku8jAFd_-9
"""

#1 Check leap year

year = int(input("Enter a year: "))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a leap year.")
else:
    print(f"{year} is not a leap year.")

#2 Largest amongst three numbers

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
num3 = float(input("Enter third number: "))

if num1 >= num2 and num1 >= num3:
    largest = num1
elif num2 >= num1 and num2 >= num3:
    largest = num2
else:
    largest = num3

print("The largest number is:", largest)

#3 Check a number is positive, negative or 0

num = float(input("Enter a number: "))

if num > 0:
    print("The number is positive.")
elif num < 0:
    print("The number is negative.")
else:
    print("The number is zero.")

#4
product_code = int(input("Enter the product code (1 for Battery Based Toys, 2 for Key-based Toys, 3 for Electrical Charging Based Toys): "))

if product_code not in [1, 2, 3]:
    print("Invalid product code! Program terminated.")
    exit()

order_amount = float(input("Enter the order amount: "))

discount = 0

# Battery Based Toys
if product_code == 1:
    if order_amount > 1000:
        discount = 0.10 * order_amount

# Key-based Toys
elif product_code == 2:
    if order_amount > 100:
        discount = 0.05 * order_amount

# Electrical Charging Based Toys
elif product_code == 3:
    if order_amount > 500:
        discount = 0.10 * order_amount

net_amount = order_amount - discount

print(f"Order Amount: ₹{order_amount}")
print(f"Discount: ₹{discount}")
print(f"Net Amount to be Paid: ₹{net_amount}")