# -*- coding: utf-8 -*-
"""DANLC_Lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ruVfX8NpE7Ylef2i_Xl-rqeJXmrBSl1I
"""

#1
def div(a,b: int):
    return a/b

a = int(input("Enter 1st number: "))
b = int(input("Enter 2nd number: "))
print(f"Division of {a} & {b}:", div(a,b))

#2
def square(a):
    return a**2

a = int(input("Enter number: "))
print(f"Square of {a}:", square(a))

#3
numbers = []
for i in range(5):
    number = float(input(f"Enter {i+1} number : "))
    numbers.append(number)

maximum = max(numbers)
minimum = min(numbers)

print(f"The maximum value is: {maximum}")
print(f"The minimum value is: {minimum}")

#4
name = input("Enter your name: ")

lowercase = name.lower()
print(f"Your name in lowercase is: {lowercase}")